CREATE TABLE IF NOT EXISTS listings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  original_price BIGINT UNSIGNED NULL,
  condition ENUM('NEW','LIKE_NEW','GOOD','FAIR','POOR') NOT NULL,
  status ENUM('DRAFT','PENDING','ACTIVE','REJECTED','HIDDEN','RESERVED','SOLD') NOT NULL DEFAULT 'DRAFT',
  reject_reason VARCHAR(255) NULL,
  hide_reason VARCHAR(255) NULL,
  reserved_offer_id BIGINT UNSIGNED NULL,
  address VARCHAR(255) NULL,
  latitude DECIMAL(10,8) NOT NULL,
  longitude DECIMAL(11,8) NOT NULL,
  location POINT SRID 4326 NOT NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  offer_count INT UNSIGNED NOT NULL DEFAULT 0,
  wishlist_count INT UNSIGNED NOT NULL DEFAULT 0,
  is_boosted BOOLEAN NOT NULL DEFAULT FALSE,
  boosted_until DATETIME NULL,
  published_at DATETIME NULL,
  sold_at DATETIME NULL,
  version INT UNSIGNED NOT NULL DEFAULT 0,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  INDEX idx_listings_seller_status (seller_id, status),
  INDEX idx_listings_cat_status_price (category_id, status, price),
  INDEX idx_listings_status_published (status, published_at DESC),
  INDEX idx_listings_status_boosted (status, is_boosted, published_at DESC),
  SPATIAL INDEX idx_listings_location (location),
  FULLTEXT INDEX idx_listings_fts (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
