CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  offer_id BIGINT UNSIGNED UNIQUE NOT NULL,
  buyer_id BIGINT UNSIGNED NOT NULL,
  seller_id BIGINT UNSIGNED NOT NULL,
  amount BIGINT UNSIGNED NOT NULL,
  commission_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  net_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  payment_method ENUM('WALLET','VIETQR','MOMO','ZALOPAY','CARD','COD','MEETUP') NOT NULL,
  payment_status ENUM('PENDING_PAYMENT','PAID_IN_ESCROW','COD_PENDING','SHIPPED','DISPUTED','COMPLETED','REFUNDED','PARTIALLY_REFUNDED','CANCELLED') NOT NULL DEFAULT 'PENDING_PAYMENT',
  delivery_method ENUM('SHIP','MEETUP') NOT NULL,
  shipping_address VARCHAR(500) NULL,
  tracking_number VARCHAR(100) NULL,
  shipped_at DATETIME NULL,
  received_at DATETIME NULL,
  auto_release_at DATETIME NULL,
  escrow_released_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE RESTRICT,
  FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE RESTRICT,
  FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE RESTRICT,
  INDEX idx_tx_buyer_status (buyer_id, payment_status, created_at DESC),
  INDEX idx_tx_seller_status (seller_id, payment_status, created_at DESC),
  INDEX idx_tx_listing (listing_id),
  INDEX idx_tx_auto_release (payment_status, auto_release_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
