CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  type ENUM('OFFER_CREATED','OFFER_ACCEPTED','OFFER_REJECTED','LISTING_APPROVED','LISTING_REJECTED','TRANSACTION_COMPLETED','REVIEW_RECEIVED','MESSAGE_RECEIVED','DISPUTE_OPENED','DISPUTE_RESOLVED','WITHDRAWAL_APPROVED','WITHDRAWAL_REJECTED','SYSTEM') NOT NULL,
  title VARCHAR(200) NOT NULL,
  content VARCHAR(500) NULL,
  reference_type VARCHAR(50) NULL,
  reference_id BIGINT UNSIGNED NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_notif_user_read (user_id, is_read, created_at DESC),
  INDEX idx_notif_user_created (user_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
