CREATE TABLE IF NOT EXISTS banned_keywords (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  keyword VARCHAR(100) UNIQUE NOT NULL,
  category ENUM('PROHIBITED_GOODS','FRAUD','CONTACT','OTHER') NOT NULL,
  action ENUM('FLAG','BLOCK') NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_banned_active (is_active, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
